import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

class IRLVisualizer:
    def __init__(self, mdp_data, theta):
        """
        mdp_data: output de MDPBuilder.build_all()
        theta: pesos aprendidos (learned_theta) de MaxEnt IRL
        """
        self.mdp = mdp_data
        self.theta = theta
        self.feature_matrix = mdp_data["feature_matrix"]
        
        # Nombres legibles para las características de tu estado
        self.feature_names = [
            "Speed Dev (Efficiency)", 
            "Abs Long Accel (Comfort)", 
            "Abs Lat Accel (Comfort)", 
            "Abs Jerk (Comfort)", 
            "Front Risk (Safety)", 
            "Collision (Safety)", 
            "Interaction"
        ]

    def plot_trajectory_comparisonVT(self, expert_df, simulated_df, experiment2):
        """Compares the trajectory of a human expert with simulated trajectories"""
        plt.figure(figsize=(10, 5))
        # velocity against time
        plt.subplot(1, 2, 1)
        
        # This forces both lines to start at X = 0
        if (not experiment2):
            plt.plot(range(len(expert_df)), expert_df["computed_v"], label="Human Expert", color="blue", linewidth=2.5)
            plt.plot(range(len(simulated_df)), simulated_df["v"], '--', label="IRL Agent", color="orange", linewidth=2.5)
        else:
            plt.plot(range(len(expert_df)), expert_df["v"], label="Aggressive Agent", color="red", linewidth=2.5)
            plt.plot(range(len(simulated_df)), simulated_df["v"], '--', label="Conservative Agent", color="green", linewidth=2.5)

        plt.xlabel("Simulation Steps")
        plt.ylabel("Speed (m/s)")
        plt.title("Speed vs Time")
        plt.legend()
        plt.grid(True, alpha=0.3)

    def plot_trajectory_comparison(self, expert_df, simulated_df, experiment2):
        """Compares the trajectory of a human expert with the one generated by your agent."""
        plt.figure(figsize=(10, 5))
        
        # Dibujar los carriles de la autopista M40
        for lane_y in [500, 503, 506]:
            plt.axhline(y=lane_y, color="gray", linestyle="--", alpha=0.5, label="Lane Center" if lane_y == 500 else "")

        # Dibujar trayectorias
        if (not experiment2):
            plt.plot(expert_df["x"], expert_df["y"], label="Human Expert", color="blue", linewidth=2.5)
            plt.plot(simulated_df["x"], simulated_df["y"], '--', label="IRL Agent", color="orange", linewidth=2.5)
        else:
            title = ""
            plt.plot(expert_df["x"], expert_df["y"], label="Aggressive Agent", color="red", linewidth=2.5)
            plt.plot(simulated_df["x"], simulated_df["y"], '--', label="Conservative Agent", color="green", linewidth=2.5)
        #plot velocity only of simulated and expert
        
        #print(simulated_df.columns)
        plt.xlabel("X position (meters)")
        plt.ylabel("Y position (meters)")
        
        # Evitar etiquetas de carril duplicadas en la leyenda
        handles, labels = plt.gca().get_legend_handles_labels()
        by_label = dict(zip(labels, handles))
        plt.legend(by_label.values(), by_label.keys())
        
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()

    def plot_reward_weights(self):
        """Muestra los pesos theta aprendidos para cada característica."""
        plt.figure(figsize=(8, 5))
        
        # Usar colores según si el peso es positivo (recompensa) o negativo (penalización)
        colors = ['green' if val > 0 else 'red' for val in self.theta]
        
        sns.barplot(x=self.feature_names, y=self.theta, palette=colors)
        plt.title("Learned Reward Weights ($\theta$)")
        plt.ylabel("Weight Value")
        plt.xticks(rotation=45)
        plt.axhline(0, color='black', linewidth=1)
        plt.grid(axis='y', alpha=0.3)
        plt.tight_layout()
        plt.show()

    def plot_action_distribution(self, trajectories):
        """Muestra qué acciones toma el experto más frecuentemente."""
        actions = []
        for _, traj in trajectories:
            for (_, a) in traj:
                actions.append(a)

        plt.figure(figsize=(10, 5))
        sns.histplot(actions, bins=self.mdp["n_actions"], discrete=True, color='purple', alpha=0.7)
        plt.title("Action Distribution in Expert Data")
        plt.xlabel("Action ID (0 to 14)")
        plt.ylabel("Frequency")
        plt.xticks(range(self.mdp["n_actions"]))
        plt.grid(axis='y', alpha=0.3)
        plt.tight_layout()
        plt.show()

    def normalize_pair(self, exp_values, sim_values):
        combined = np.concatenate([exp_values, sim_values])

        min_val = combined.min()
        max_val = combined.max()

        # Avoid division by zero
        if max_val - min_val < 1e-8:
            return np.zeros_like(exp_values), np.zeros_like(sim_values)

        exp_norm = (exp_values - min_val) / (max_val - min_val)
        sim_norm = (sim_values - min_val) / (max_val - min_val)

        return exp_norm, sim_norm

    def plot_feature_expectations_matching(self, expert_df, simulated_df):
        """
        Genera un diagrama de barras doble para demostrar que el Agente
        ha aprendido a igualar las características (Feature Expectations) del Experto.
        """
        feature_names = [
        "Speed",
        "Long. Accel",
        "Lat. Accel",
        "Jerk",
        "Front Risk",
        "Collision",
        "Interaction"
        ]
        min_len = min(len(simulated_df), len(expert_df))
        
        ## Expert
        th = expert_df['time_headway'].fillna(0.0).iloc[:min_len].values
        v_exp = expert_df['computed_v'].iloc[:min_len].values
        acc_exp = expert_df['longitudinal_acceleration'].iloc[:min_len].values
        lat_acc_exp = expert_df['lateral_acceleration'].iloc[:min_len].values
        jerk_exp = expert_df['longitudinal_jerk'].iloc[:min_len].values
        front_risk_exp = np.where(th > 0, np.exp(-th), 0.0)
        distance_exp = np.where(th > 0, th * v_exp, 999.0)
        collision_exp = np.where(distance_exp < 2.0, 1.0, 0.0)
        interaction_exp = np.where((acc_exp < 0) & (front_risk_exp > 0.05), np.abs(acc_exp), 0.0)

        ## Simulated Agent
        v_sim = simulated_df['v'].iloc[:min_len].values
        acc_sim = simulated_df['accel'].iloc[:min_len].values
        lat_acc_sim = simulated_df['lat_accel'].iloc[:min_len].values
        jerk_sim = simulated_df['jerk'].iloc[:min_len].values
        front_risk_sim = simulated_df['front_risk'].iloc[:min_len].values
        collision_sim = simulated_df['collision'].iloc[:min_len].values
        interaction_sim = simulated_df['interaction'].iloc[:min_len].values

        v_exp_n, v_sim_n = self.normalize_pair(np.abs(v_exp), np.abs(v_sim))

        acc_exp_n, acc_sim_n = self.normalize_pair(
            np.abs(acc_exp),
            np.abs(acc_sim)
        )

        lat_acc_exp_n, lat_acc_sim_n = self.normalize_pair(
            np.abs(lat_acc_exp),
            np.abs(lat_acc_sim)
        )

        jerk_exp_n, jerk_sim_n = self.normalize_pair(
            np.abs(jerk_exp),
            np.abs(jerk_sim)
        )

        front_risk_exp_n, front_risk_sim_n = self.normalize_pair(
            np.abs(front_risk_exp),
            np.abs(front_risk_sim)
        )

        collision_exp_n, collision_sim_n = self.normalize_pair(
            np.abs(collision_exp),
            np.abs(collision_sim)
        )

        interaction_exp_n, interaction_sim_n = self.normalize_pair(
            np.abs(interaction_exp),
            np.abs(interaction_sim)
        )
        
        # Agrupar las características del experto
        expert_features = np.array([
            np.sum(np.abs(v_exp_n)),
            np.sum(np.abs(acc_exp_n)),
            np.sum(np.abs(lat_acc_exp_n)),
            np.sum(np.abs(jerk_exp_n)),
            np.sum(front_risk_exp_n),
            np.sum(collision_exp_n),
            np.sum(interaction_exp_n)
        ])
        
        # Extraer las características del AGENTE (ya calculadas en DrivingEnv.simulate_agent)
        agent_features = np.array([
            np.sum(np.abs(v_sim_n)),
            np.sum(np.abs(acc_sim_n)),
            np.sum(np.abs(lat_acc_sim_n)),
            np.sum(np.abs(jerk_sim_n)),
            np.sum(front_risk_sim_n),
            np.sum(collision_sim_n),
            np.sum(interaction_sim_n)
        ])

        # Normalizar por la longitud de la trayectoria para obtener promedios
        expert_features = expert_features / min_len
        agent_features = agent_features / min_len

        x = np.arange(len(expert_features))
        width = 0.35

        plt.figure(figsize=(10, 6))
        bars1 = plt.bar(x - width/2, expert_features, width, label='Human Expert', color='#1f77b4', edgecolor='black')
        bars2 = plt.bar(x + width/2, agent_features, width, label='MaxEnt IRL Agent', color='#ff7f0e', edgecolor='black')

        plt.ylabel('Mean Absolute Value')
        plt.title('Feature Expectation Matching: Expert vs. Agent')
        plt.xticks(x, feature_names, rotation=15)
        plt.legend()
        plt.grid(axis='y', linestyle='--', alpha=0.7)

        #Values on top of bars
        for bars in [bars1, bars2]:
            for bar in bars:
                height = bar.get_height()
                plt.text(
                    bar.get_x() + bar.get_width()/2,
                    height,
                    f'{height:.2f}',
                    ha='center',
                    va='bottom',
                    fontsize=8
                )
        
        # Guardar y mostrar
        plt.tight_layout()
        plt.savefig("results/feature_expectation_matching.png", dpi=300)
        plt.show()

    def plot_kinematics_over_time(self, expert_df, simulated_df, experiment2=False):
        """
        Sustituye/Mejora a plot_trajectory_comparisonVT.
        Muestra Velocidad y Aceleración sincronizadas en el tiempo.
        Ideal para detectar 'Failure Cases' y comportamiento oscilatorio.
        """
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)
        time_steps = range(len(expert_df))

        #  Gráfica 1: Velocidad 
        if (not experiment2):
            ax1.plot(time_steps, expert_df["computed_v"], label="Human Expert", color="#1f77b4", linewidth=2.5)
            ax1.plot(time_steps, simulated_df["v"], label="Simulated Agent", color="#ff7f0e", linestyle="--", linewidth=2.5)
        else:
            ax1.plot(time_steps, expert_df["v"], label="Aggresive Agent", color="#d70909", linewidth=2.5)
            ax1.plot(time_steps, simulated_df["v"], label="Conservative Agent", color="#2ca02c", linestyle="--", linewidth=2.5)

        ax1.set_ylabel("Velocity (m/s)", fontsize=12)
        ax1.set_title("Kinematic Evolution Over Time", fontsize=14, fontweight='bold')
        ax1.legend(loc="best")
        ax1.grid(True, linestyle='--', alpha=0.6)

        #  Gráfica 2: Aceleración 
        if (not experiment2):
            ax2.plot(time_steps, expert_df["acceleration"], label="Human Expert", color="#1f77b4", linewidth=2.5)
            ax2.plot(time_steps, simulated_df["accel"], label="Simulated Agent", color="#ff7f0e", linestyle="--", linewidth=2.5)
        else:
            ax2.plot(time_steps, expert_df["accel"], label="Aggresive Agent", color="#d70909", linewidth=2.5)
            ax2.plot(time_steps, simulated_df["accel"], label="Conservative Agent", color="#2ca02c", linestyle="--", linewidth=2.5)

        ax2.set_ylabel("Acceleration (m/s²)", fontsize=12)
        ax2.set_xlabel("Time Step (Frames)", fontsize=12)
        ax2.grid(True, linestyle='--', alpha=0.6)

        # Guardar y mostrar
        plt.tight_layout()
        plt.savefig("results/kinematics_over_time.png", dpi=300)
        plt.show()

    def plot_style_comparison(self, agg_sim_df, cons_sim_df, agg_exp_df, cons_exp_df):
        """
        Plots a side-by-side comparison of the Aggressive and Conservative 
        simulated agents to demonstrate behavioral modeling convergence. For experiment 2.
        """
        # Make two seperate plots: one for velocity and one for lateral position (y)
        #fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
        # Plot 1: Longitudinal Velocity Profile Over Time
        plt.figure(figsize=(10, 5))
        plt.plot(agg_sim_df["v"], label="Aggressive Agent", color="#d62728", linewidth=2.5)
        plt.plot(cons_sim_df["v"], label="Conservative Agent", color="#2ca02c", linewidth=2.5)
        plt.plot(agg_exp_df["computed_v"], label="Aggressive Expert", color="#1408f0", linestyle="--", linewidth=2.5)
        plt.plot(cons_exp_df["computed_v"], label="Conservative Expert", color="#f67708", linestyle="--", linewidth=2.5)
        #ax1.set_title("Velocity Selection Profile")
        plt.xlabel("Time Frame Step")
        plt.ylabel("Speed (m/s)")
        plt.grid(True, linestyle="--", alpha=0.5)
        plt.legend()
        plt.tight_layout()
        plt.show()
        
        # Plot 2: Lateral Positioning Distribution (Lane Selection)
        plt.figure(figsize=(10, 5))
        plt.plot(cons_sim_df["y"], label="Aggressive Path", color="#d62728", linestyle="--")
        plt.plot(agg_sim_df["y"], label="Conservative Path", color="#2ca02c", linestyle="-")
        plt.plot(agg_exp_df["y"], label="Aggressive Expert", color="#1408f0", linestyle="--", linewidth=2.5)
        plt.plot(cons_exp_df["y"], label="Conservative Expert", color="#f67708", linestyle="-", linewidth=2.5)
        #ax2.set_title("Lateral Lane Deviation Profile")
        plt.xlabel("Time Frame Step")
        plt.ylabel("Lateral Position Offset (m)")
        plt.grid(True, linestyle="--", alpha=0.5)
        plt.legend()
        
        #plt.suptitle("Experiment 2: Driving Styles Trajectory Comparison", fontsize=14, fontweight='bold')
        plt.tight_layout()
        #plt.savefig("results/experiment2_style_comparison.png", dpi=300)
        plt.show()

    def plot_policy_heatmap(self, policy, expert_trajectories, top_n_states=30):
        """
        Versión corregida: Genera un mapa de calor de pi(a|s).
        Muestra qué acciones prefiere el agente en los estados que el experto visitó.
        """
        # 1. Reconstruir etiquetas de acciones siguiendo la lógica de MDPBuilder
        v_actions = ["-1.5", "-0.75", "0 (maintain)", "+0.75", "+1.5"]
        l_actions = ["Left", "Center", "Right"]
        
        action_labels = []
        for v in v_actions:
            for l in l_actions:
                action_labels.append(f"{v} | {l}")

        # 2. Obtener una muestra de estados que el EXPERTO realmente visitó
        # (Esto hace que el gráfico tenga sentido real)
        visited_states = []
        for _, traj in expert_trajectories[:5]: # Miramos las primeras 5 trayectorias
            for state_idx, _ in traj:
                if state_idx not in visited_states:
                    visited_states.append(state_idx)
        
        # Limitamos para que el gráfico no sea gigante
        sample_states = visited_states[:top_n_states]
        subset_policy = policy[sample_states, :]
        
        # 3. Dibujar el Heatmap
        plt.figure(figsize=(12, 8))
        ax = sns.heatmap(
            subset_policy.T, 
            cmap="YlGnBu", 
            xticklabels=sample_states,
            yticklabels=action_labels,
            cbar_kws={'label': 'Probabilidad $\pi(a|s)$'},
            linewidths=.5
        )
        
        plt.title("Política Aprendida: Probabilidad de Acción por Estado", fontsize=14, pad=20)
        plt.xlabel("ID del Estado (Visitados por el Experto)", fontsize=12)
        plt.ylabel("Espacio de Acciones Discreto", fontsize=12)
        
        plt.tight_layout()
        plt.savefig("results/policy_heatmap_fixed.png", dpi=300)
        plt.show()

    
    def run_all(self, expert_df, simulated_df, test_trajectories, policy, experiment2=False):
        """Ejecuta todas las visualizaciones a la vez."""
        
        print("Visualizing Trajectories...")
        self.plot_trajectory_comparison(expert_df, simulated_df, experiment2)
        self.plot_trajectory_comparisonVT(expert_df, simulated_df,experiment2)

        print("Visualizing Kinematics Over Time...")
        self.plot_kinematics_over_time(expert_df, simulated_df, experiment2)

        print("Visualizing Reward Weights...")
        self.plot_reward_weights()

        if experiment2 == False:

            print("Visualizing Action Distributions...")
            self.plot_action_distribution(test_trajectories)

            print("Visualizing Feature Expectation Matching...")
            self.plot_feature_expectations_matching(expert_df, simulated_df)

def import_data_for_styles():
    """
    Carga los DataFrames de las trayectorias simuladas para ambos estilos
    y los devuelve para su uso en la función de comparación de estilos.
    """
    # Cargar trayectorias simuladas desde CSV
    try:
    # Load style dataframes directly
        agg_sim = pd.read_csv("results/aggressive_simulated_trajectory.csv")
        cons_sim = pd.read_csv("results/conservative_simulated_trajectory.csv")
        agg_exp = pd.read_csv("results/aggressive_expert_trajectory.csv")
        cons_exp = pd.read_csv("results/conservative_expert_trajectory.csv")
    
        with open("results/styles_artifacts.pkl", "rb") as f:
            styles = pickle.load(f)
        
        visualizer = IRLVisualizer(mdp_data=styles["conservative"]["mdp_data"], theta=styles["conservative"]["theta"])

    except FileNotFoundError:
        print("Styles files not found. Run mainDrivingStylesExperiment.py first.")
    # Return the loaded dataframes and visualizer instance and policy if needed
    return agg_sim, cons_sim, visualizer, styles["aggressive"]["policy"], styles["conservative"]["policy"], agg_exp, cons_exp

if __name__ == "__main__":
    import pickle
    import os

    results_dir = "results"
    
    print("Loading saved artifacts...")
    experiment2 = False # Toggle True if you want to visualize experiment 2 results.

    if experiment2:
        print("Running Experiment 2 Visualizations...")
        agg_sim, cons_sim, visualizer, agg_policy, cons_policy, agg_exp, cons_exp = import_data_for_styles()
        #visualizer.run_all(
        #    expert_df=agg_sim, 
        #    simulated_df=cons_sim, 
        #    test_trajectories=0,
        #    policy=agg_policy,
        #    experiment2=True
        #)
        visualizer.plot_style_comparison(agg_sim, cons_sim, agg_exp, cons_exp)

    else:
    
        try:
            # 1. Load the CSV trajectories
            expert_df = pd.read_csv(f"{results_dir}/expert_trajectory.csv")
            sim_df = pd.read_csv(f"{results_dir}/simulated_trajectory.csv")

            # 2. Load the Pickle objects
            with open(f"{results_dir}/irl_artifacts.pkl", "rb") as f:
                artifacts = pickle.load(f)

            theta = artifacts["theta"]
            mdp_data = artifacts["mdp_data"]
            test_trajectories = artifacts["test_trajectories"]
            policy = artifacts.get("policy", None) 

            visualizer = IRLVisualizer(mdp_data=mdp_data, theta=theta)
            # 3. Initialize Visualizer and Run
            visualizer.run_all(
                expert_df=expert_df, 
                simulated_df=sim_df, 
                test_trajectories=test_trajectories,
                policy=policy,
                experiment2=False
                )
        except FileNotFoundError:
            print("Error: Could not find the saved files.")        